import java.awt.Color;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.io.PrintStream;
import java.math.BigInteger;
import java.net.InetAddress;
import java.net.Socket;
import java.net.UnknownHostException;
import java.util.concurrent.TimeoutException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JColorChooser;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author André Moura
 */
public class Janela extends javax.swing.JFrame {

    /**
     * Creates new form Janela
     */
    
    //Comandos
    private static Janela frame;
    JColorChooser escolhe = new JColorChooser();
    Color cor = new Color(255,255,255);
    static Cliente cliente = null;
    static DataInputStream din;
   //static PrintStream dout;
    //static PrintStream dout;
    //int [] rgb = new int[3];
    static DataOutputStream dout;
    static boolean teste = false;
    
    public Janela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        janelaSucesso = new javax.swing.JDialog();
        sucessoOk = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        janelaprogresso = new javax.swing.JDialog();
        barraProgresso = new javax.swing.JProgressBar();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        comecar_OK = new javax.swing.JButton();
        cancelar_OK = new javax.swing.JButton();
        tabMain = new javax.swing.JTabbedPane();
        Main = new javax.swing.JPanel();
        painelUmodo = new javax.swing.JPanel();
        manual = new javax.swing.JRadioButton();
        temp_modo = new javax.swing.JRadioButton();
        rainBow = new javax.swing.JRadioButton();
        painelConnect = new javax.swing.JPanel();
        textConnect = new javax.swing.JTextField();
        connect = new javax.swing.JButton();
        Sair = new javax.swing.JButton();
        search = new javax.swing.JButton();
        painelControlo = new javax.swing.JPanel();
        sliderTemp = new javax.swing.JSlider();
        intensidade_label = new javax.swing.JLabel();
        escolher_cor = new javax.swing.JButton();
        cor_Label = new javax.swing.JLabel();
        painelTemp = new javax.swing.JPanel();
        labelTemp = new javax.swing.JLabel();
        tempRegisto = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();

        janelaSucesso.setBounds(new java.awt.Rectangle(50, 50, 100, 100));
        janelaSucesso.setFont(new java.awt.Font("18thCentury", 0, 10)); // NOI18N
        janelaSucesso.setLocationByPlatform(true);
        janelaSucesso.setMinimumSize(new java.awt.Dimension(255, 154));
        janelaSucesso.setResizable(false);

        sucessoOk.setText("OK");
        sucessoOk.setToolTipText("");
        sucessoOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sucessoOkActionPerformed(evt);
            }
        });

        jLabel2.setText("Ligado ao servidor com sucesso");

        org.jdesktop.layout.GroupLayout janelaSucessoLayout = new org.jdesktop.layout.GroupLayout(janelaSucesso.getContentPane());
        janelaSucesso.getContentPane().setLayout(janelaSucessoLayout);
        janelaSucessoLayout.setHorizontalGroup(
            janelaSucessoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(janelaSucessoLayout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .add(jLabel2)
                .add(49, 49, 49))
            .add(janelaSucessoLayout.createSequentialGroup()
                .add(89, 89, 89)
                .add(sucessoOk, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 73, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        janelaSucessoLayout.setVerticalGroup(
            janelaSucessoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, janelaSucessoLayout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .add(jLabel2)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(sucessoOk)
                .add(53, 53, 53))
        );

        janelaprogresso.setLocationByPlatform(true);
        janelaprogresso.setMinimumSize(new java.awt.Dimension(346, 100));
        janelaprogresso.setResizable(false);

        barraProgresso.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                barraProgressoStateChanged(evt);
            }
        });

        jLabel6.setText("Progresso");

        jLabel7.setText("Dispositivo Encontrado:");

        jLabel8.setText("N/A");

        comecar_OK.setText("Começar");

        cancelar_OK.setText("Cancelar");
        cancelar_OK.setEnabled(false);

        org.jdesktop.layout.GroupLayout janelaprogressoLayout = new org.jdesktop.layout.GroupLayout(janelaprogresso.getContentPane());
        janelaprogresso.getContentPane().setLayout(janelaprogressoLayout);
        janelaprogressoLayout.setHorizontalGroup(
            janelaprogressoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(janelaprogressoLayout.createSequentialGroup()
                .add(22, 22, 22)
                .add(janelaprogressoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(janelaprogressoLayout.createSequentialGroup()
                        .add(jLabel6, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(barraProgresso, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 242, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(janelaprogressoLayout.createSequentialGroup()
                        .add(jLabel7)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(jLabel8)
                        .add(18, 18, 18)
                        .add(comecar_OK)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(cancelar_OK)))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        janelaprogressoLayout.setVerticalGroup(
            janelaprogressoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(janelaprogressoLayout.createSequentialGroup()
                .addContainerGap()
                .add(janelaprogressoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jLabel6, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                    .add(barraProgresso, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(janelaprogressoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel8)
                    .add(comecar_OK)
                    .add(jLabel7)
                    .add(cancelar_OK))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabMain.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tabMain.setName(""); // NOI18N

        painelUmodo.setBorder(javax.swing.BorderFactory.createTitledBorder("User Mode"));

        manual.setSelected(true);
        buttonGroup1.add(manual);
        manual.setText("Manual");
        manual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manualActionPerformed(evt);
            }
        });

        buttonGroup1.add(temp_modo);
        temp_modo.setText("Temperatura");
        temp_modo.setToolTipText("");
        temp_modo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                temp_modoActionPerformed(evt);
            }
        });

        buttonGroup1.add(rainBow);
        rainBow.setText("RainBow");
        rainBow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rainBowActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout painelUmodoLayout = new org.jdesktop.layout.GroupLayout(painelUmodo);
        painelUmodo.setLayout(painelUmodoLayout);
        painelUmodoLayout.setHorizontalGroup(
            painelUmodoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(painelUmodoLayout.createSequentialGroup()
                .addContainerGap()
                .add(painelUmodoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(rainBow)
                    .add(temp_modo)
                    .add(manual))
                .addContainerGap(224, Short.MAX_VALUE))
        );
        painelUmodoLayout.setVerticalGroup(
            painelUmodoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(painelUmodoLayout.createSequentialGroup()
                .addContainerGap()
                .add(manual)
                .add(18, 18, 18)
                .add(temp_modo)
                .add(18, 18, 18)
                .add(rainBow)
                .addContainerGap(102, Short.MAX_VALUE))
        );

        painelConnect.setBorder(javax.swing.BorderFactory.createTitledBorder("Connect"));
        painelConnect.setToolTipText("");

        textConnect.setToolTipText("");
        textConnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textConnectActionPerformed(evt);
            }
        });

        connect.setText("Connect");
        connect.setActionCommand("Entrar");
        connect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connectActionPerformed(evt);
            }
        });

        Sair.setText("Sair");
        Sair.setEnabled(false);
        Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SairActionPerformed(evt);
            }
        });

        search.setText("Search");
        search.setActionCommand("Entrar");
        search.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                searchStateChanged(evt);
            }
        });
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout painelConnectLayout = new org.jdesktop.layout.GroupLayout(painelConnect);
        painelConnect.setLayout(painelConnectLayout);
        painelConnectLayout.setHorizontalGroup(
            painelConnectLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(painelConnectLayout.createSequentialGroup()
                .add(textConnect, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 173, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(painelConnectLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(search, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(connect, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(Sair)
                .add(0, 0, Short.MAX_VALUE))
        );
        painelConnectLayout.setVerticalGroup(
            painelConnectLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(painelConnectLayout.createSequentialGroup()
                .add(painelConnectLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(textConnect, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(connect)
                    .add(Sair))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(search)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        painelControlo.setBorder(javax.swing.BorderFactory.createTitledBorder("Controlo"));

        sliderTemp.setMinimum(10);
        sliderTemp.setMinorTickSpacing(20);
        sliderTemp.setPaintLabels(true);
        sliderTemp.setPaintTicks(true);
        sliderTemp.setSnapToTicks(true);
        sliderTemp.setToolTipText("Escolha a intensidade da Lampada");
        sliderTemp.setEnabled(false);
        sliderTemp.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderTempStateChanged(evt);
            }
        });

        intensidade_label.setText("Intensidade");
        intensidade_label.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        intensidade_label.setEnabled(false);

        escolher_cor.setText("Escolher");
        escolher_cor.setEnabled(false);
        escolher_cor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                escolher_corActionPerformed(evt);
            }
        });

        cor_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cor_Label.setText("Cor");
        cor_Label.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        cor_Label.setEnabled(false);

        org.jdesktop.layout.GroupLayout painelControloLayout = new org.jdesktop.layout.GroupLayout(painelControlo);
        painelControlo.setLayout(painelControloLayout);
        painelControloLayout.setHorizontalGroup(
            painelControloLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, painelControloLayout.createSequentialGroup()
                .addContainerGap()
                .add(painelControloLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, cor_Label, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 64, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(intensidade_label, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 64, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(painelControloLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(sliderTemp, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(painelControloLayout.createSequentialGroup()
                        .add(47, 47, 47)
                        .add(escolher_cor, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 83, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .add(305, 305, 305))
        );
        painelControloLayout.setVerticalGroup(
            painelControloLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(painelControloLayout.createSequentialGroup()
                .addContainerGap()
                .add(painelControloLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(intensidade_label, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 31, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(sliderTemp, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(painelControloLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(cor_Label, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 29, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(escolher_cor))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        painelTemp.setBorder(javax.swing.BorderFactory.createTitledBorder("Temperatura"));

        labelTemp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTemp.setText("jLabel5");

        org.jdesktop.layout.GroupLayout painelTempLayout = new org.jdesktop.layout.GroupLayout(painelTemp);
        painelTemp.setLayout(painelTempLayout);
        painelTempLayout.setHorizontalGroup(
            painelTempLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(painelTempLayout.createSequentialGroup()
                .add(labelTemp, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 72, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(0, 289, Short.MAX_VALUE))
        );
        painelTempLayout.setVerticalGroup(
            painelTempLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(painelTempLayout.createSequentialGroup()
                .addContainerGap()
                .add(labelTemp, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 52, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout MainLayout = new org.jdesktop.layout.GroupLayout(Main);
        Main.setLayout(MainLayout);
        MainLayout.setHorizontalGroup(
            MainLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(MainLayout.createSequentialGroup()
                .addContainerGap()
                .add(MainLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(painelConnect, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(painelUmodo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(MainLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(painelControlo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 373, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(painelTemp, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        MainLayout.setVerticalGroup(
            MainLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(MainLayout.createSequentialGroup()
                .addContainerGap()
                .add(MainLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(MainLayout.createSequentialGroup()
                        .add(painelControlo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(18, 18, 18)
                        .add(painelTemp, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(0, 0, Short.MAX_VALUE))
                    .add(MainLayout.createSequentialGroup()
                        .add(painelConnect, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(painelUmodo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        tabMain.addTab("Principal", Main);

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 732, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 334, Short.MAX_VALUE)
        );

        org.jdesktop.layout.GroupLayout tempRegistoLayout = new org.jdesktop.layout.GroupLayout(tempRegisto);
        tempRegisto.setLayout(tempRegistoLayout);
        tempRegistoLayout.setHorizontalGroup(
            tempRegistoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(tempRegistoLayout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        tempRegistoLayout.setVerticalGroup(
            tempRegistoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(tempRegistoLayout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabMain.addTab("Grafico", tempRegisto);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(1, 1, 1)
                .add(tabMain))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(tabMain)
        );

        tabMain.getAccessibleContext().setAccessibleName("Principal");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void connectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connectActionPerformed
        
        try {
        connectAt(textConnect.getText(), true);
        }
         catch (IOException ex) {
        Logger.getLogger(Janela.class.getName()).log(Level.SEVERE, null, ex);
        }
         catch (TimeoutException ex) {
                Logger.getLogger(Janela.class.getName()).log(Level.SEVERE, null, ex);
           }
        if(cliente.getCliente() == null){
            System.out.println("Erro ao conectar");
            return;
        }
        grayConnect(true);
        
    }//GEN-LAST:event_connectActionPerformed

    private void SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SairActionPerformed
      
        cliente.killCurrentServ();
        cliente = null;
        System.out.println("SAIR PRESSIONADO");
        grayConnect(false);

    }//GEN-LAST:event_SairActionPerformed

    private void textConnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textConnectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textConnectActionPerformed

    private void manualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manualActionPerformed
        System.out.println("Chegou aki");
        modoManual();
    }//GEN-LAST:event_manualActionPerformed

    private void temp_modoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_temp_modoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_temp_modoActionPerformed

    private void sucessoOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sucessoOkActionPerformed
        janelaSucesso.setVisible(false);
    }//GEN-LAST:event_sucessoOkActionPerformed

    private void escolher_corActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_escolher_corActionPerformed
        
            
            cor = escolhe.showDialog(null, "Escolha uma cor", cor); //block à espera da cor
            int [] rgb = new int[4];
            rgb[0] = cor.getRed();
            rgb [1] = cor.getGreen();
            rgb[2] = cor.getBlue();
            rgb[3] = sliderTemp.getValue();
            
            cliente.setParar(true);
    
            try{
            cliente.sendData(cliente.getSETCOLOR(),rgb.length, rgb);
            }
         catch (IOException ex) {
            System.out.println("Erro ao enviar dados de cor");
        }
            cliente.getTemp().recomeçar();
       
    }//GEN-LAST:event_escolher_corActionPerformed

    private void sliderTempStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderTempStateChanged
            int [] rgb = new int[4];
            rgb[0] = cor.getRed();
            rgb[1] = cor.getGreen();
            rgb[2] = cor.getBlue();
            rgb[3] = sliderTemp.getValue();
            
            try
            {
                 cliente.setParar(true);
            }
            catch (Exception  ex) {
            System.out.println("Erro ao enviar dados de cor");
            }
    
            try{
            cliente.sendData(cliente.getSETCOLOR(), rgb.length, rgb);
            
            }
         catch (IOException ex) {
            System.out.println("Erro ao enviar dados de cor");
        }
            cliente.getTemp().recomeçar();
    }//GEN-LAST:event_sliderTempStateChanged

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        janelaprogresso.setVisible(true);
        teste = true;
    }//GEN-LAST:event_searchActionPerformed

    private void searchStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_searchStateChanged
        
    }//GEN-LAST:event_searchStateChanged

    private void barraProgressoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_barraProgressoStateChanged
        
    }//GEN-LAST:event_barraProgressoStateChanged

    private void rainBowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rainBowActionPerformed
        
        cliente.setParar(true);
        try {
            cliente.sendData(cliente.getSETMODE(), 2);
        } catch (IOException ex) {
           System.out.println("Erro ao mandar o rainbow mode");
        }
         cliente.getTemp().recomeçar();
    }//GEN-LAST:event_rainBowActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws UnknownHostException, IOException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               frame = new Janela();
               frame.setVisible(true);
            }
        });
        while(true){
           
        if(teste){
           try{
               connectAt("",false);
             } 
           catch (TimeoutException ex) {
                Logger.getLogger(Janela.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
        
 }  
       
    static protected void connectAt(String Address, boolean tipodeconnect) throws IOException, TimeoutException{
        
        cliente = new Cliente(Address, 10101, tipodeconnect, frame);
 
    }
            
    public void grayConnect(boolean check){
        
            textConnect.setEditable(!check);
            connect.setEnabled(!check);
            Sair.setEnabled(check);
            janelaSucesso.setVisible(check);
    }
    
    protected void modoManual(){ //verifica se está ligado ao server e se Modo manual está ativo, se estiver ativa os restantes componentes
       
        if(cliente.getisConnected() && manual.isSelected()){
            escolher_cor.setEnabled(true);
            cor_Label.setEnabled(true);
            sliderTemp.setEnabled(true);
            intensidade_label.setEnabled(true);
        }
  
    }
    


    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JPanel Main;
    static javax.swing.JButton Sair;
    public javax.swing.JProgressBar barraProgresso;
    javax.swing.ButtonGroup buttonGroup1;
    javax.swing.JButton cancelar_OK;
    javax.swing.JButton comecar_OK;
    static javax.swing.JButton connect;
    javax.swing.JLabel cor_Label;
    javax.swing.JButton escolher_cor;
    javax.swing.JLabel intensidade_label;
    javax.swing.JLabel jLabel2;
    javax.swing.JLabel jLabel6;
    javax.swing.JLabel jLabel7;
    javax.swing.JLabel jLabel8;
    javax.swing.JPanel jPanel1;
    static javax.swing.JDialog janelaSucesso;
    javax.swing.JDialog janelaprogresso;
    javax.swing.JLabel labelTemp;
    javax.swing.JRadioButton manual;
    javax.swing.JPanel painelConnect;
    javax.swing.JPanel painelControlo;
    javax.swing.JPanel painelTemp;
    javax.swing.JPanel painelUmodo;
    javax.swing.JRadioButton rainBow;
    static javax.swing.JButton search;
    javax.swing.JSlider sliderTemp;
    static javax.swing.JButton sucessoOk;
    javax.swing.JTabbedPane tabMain;
    javax.swing.JPanel tempRegisto;
    javax.swing.JRadioButton temp_modo;
    static javax.swing.JTextField textConnect;
    // End of variables declaration//GEN-END:variables
}